[project]
name = "black-box-pentesting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "blinker==1.7.0",
    "crewai[tools]>=0.86.0",
    "selenium>=4.31.0",
    "selenium-wire>=5.1.0",
]
