# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

web_crawling_task:
  description: >
    Go through the given webpage at base URL: {url} by using the get_page tool and choose the most appropriate action to take
    Make sure you choose the correct button to click using the click_button tool
  expected_output: >
    First note each button in the page
    ABSOLUTELY make sure you have noticed all the actions available. Not even one should remain.
    make ABSOLUTELY ABSOLUTELY sure you have performed all possible actions. Take as many iterations as you
    If you reach a dead end, go back to the base URL {url} and try something else
    If you are confused about an output, note it down, and then try another button.
    Explain each choice in detail with a timeline/step of what you did and why
    Hint: Click the Signup button, fill the form with sensible details, got to base url {url}, login with the exact fields you signed up with
  agent: web_crawler_agent