# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

web_crawling_task:
  description: >
    Go through the given webpage at base URL: {url} by using the get_page tool and choose the most appropriate action to take
    Make sure you choose the correct button to click using the click_button tool
  expected_output: >
    An explanation about what you understood in the page and why you chose to click that particular button
    Remember which buttons you saw and make sure to click and record what was the output of each
    If you reach a dead end, go back to the base URL {url} and try something else
    Explain each choice in detail with a timeline/step of what you did and why
  agent: web_crawler_agent